// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHFxBNOtwpObtumR8P-MoZRcI60-7XQI',
    appId: '1:90320497703:android:93d2fe35bf2d0754c73202',
    messagingSenderId: '90320497703',
    projectId: 'rock-of-praise-lyrics',
    storageBucket: 'rock-of-praise-lyrics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrjpzLTXRrrC23pAiy9amfpUxvzD43Fs',
    appId: '1:90320497703:ios:956aba836938ab05c73202',
    messagingSenderId: '90320497703',
    projectId: 'rock-of-praise-lyrics',
    storageBucket: 'rock-of-praise-lyrics.firebasestorage.app',
    androidClientId: '90320497703-akhb3nmukosoteola7phgm27gq94ku6i.apps.googleusercontent.com',
    iosClientId: '90320497703-ti845k7pipgpj7rpoq954qas6e8u6o9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lyrics',
  );

}