default_platform(:ios)

platform :ios do
  desc "Build the IPA"
  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    # අලුතින් Certificates හදන්න එපා, අපි දෙන එක ගන්න කියලා කියනවා
    # අපේ GitHub Workflow එකෙන් දැනටමත් මේවා Mac එකට දාලා තියෙන්නේ
    
    # Build the IPA
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      configuration: "Release",
      codesigning_identity: "Apple Distribution",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.therockofpraise.lyrics" => "Rock Of Praise Christian Songs"
        }
      },
      output_directory: "../build/ios/ipa",
      output_name: "TheRockOfPraise.ipa",
      clean: true
    )
  end

  desc "Deploy to TestFlight"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/TheRockOfPraise.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end