default_platform(:ios)

platform :ios do
  desc "Build the IPA"
  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    # මෙන්න මෙතන තමයි වෙනස් කළේ:
    # අලුතින් හදන්න එපා, තියෙන එක ගන්න කියලා අපි කියනවා
    get_certificates(api_key: api_key, generate_apple_certs: false)
    get_provisioning_profile(api_key: api_key, type: "app-store")

    # Build the IPA
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      output_directory: "../build/ios/ipa",
      output_name: "TheRockOfPraise.ipa",
      clean: true,
      api_key: api_key
    )
  end

  desc "Deploy to TestFlight"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    # Upload the IPA to TestFlight
    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/TheRockOfPraise.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end