name: iOS Production Build

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install --repo-update

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundle-install: true

      - name: Build IPA with Fastlane
        run: |
          cd ios
          fastlane build

      - name: Deploy to TestFlight
        run: |
          cd ios
          fastlane deploy

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-ipa
          path: build/ios/ipa/TheRockOfPraise.ipa
